services:
  - type: web
    name: ezehcut-backend
    env: docker
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000